# Generated by Django 5.2.11 on 2026-02-25 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('source_sha256', models.CharField(max_length=64, unique=True)),
                ('participants_n', models.IntegerField(default=0)),
                ('excluded_n', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-exam_date', '-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('source_sha256', models.CharField(max_length=64, unique=True)),
                ('exam_name', models.CharField(max_length=255)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('preview_json', models.JSONField(default=dict)),
                ('payload', models.BinaryField(blank=True, default=bytes)),
                ('status', models.CharField(choices=[('staged', 'staged'), ('imported', 'imported'), ('failed', 'failed')], default='staged', max_length=32)),
                ('error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('admission_ticket', models.CharField(blank=True, max_length=64)),
                ('custom_exam_id', models.CharField(blank=True, max_length=64)),
                ('class_name', models.CharField(blank=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['external_id'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=32)),
                ('mean_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('median_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sample_n', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_stats', to='gradebook.exam')),
            ],
            options={
                'indexes': [models.Index(fields=['exam', 'question_key'], name='gradebook_e_exam_id_b2a63c_idx')],
                'constraints': [models.UniqueConstraint(fields=('exam', 'question_key'), name='uniq_exam_question_stat')],
            },
        ),
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('total_raw', models.CharField(blank=True, max_length=255)),
                ('objective_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('subjective_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('rank_in_class', models.IntegerField(blank=True, null=True)),
                ('excluded_from_stats', models.BooleanField(default=False)),
                ('exclude_reason', models.CharField(blank=True, max_length=255)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='gradebook.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_scores', to='gradebook.student')),
            ],
            options={
                'indexes': [models.Index(fields=['exam', 'excluded_from_stats'], name='gradebook_e_exam_id_1ee1e8_idx')],
                'constraints': [models.UniqueConstraint(fields=('exam', 'student'), name='uniq_exam_student')],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=32)),
                ('score_value', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_scores', to='gradebook.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_scores', to='gradebook.student')),
            ],
            options={
                'indexes': [models.Index(fields=['exam', 'question_key'], name='gradebook_e_exam_id_3a6406_idx'), models.Index(fields=['exam', 'question_key', 'score_value'], name='gradebook_e_exam_id_853345_idx')],
                'constraints': [models.UniqueConstraint(fields=('exam', 'student', 'question_key'), name='uniq_exam_student_question')],
            },
        ),
    ]
