# Generated by Django 5.2.11 on 2026-02-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examimport',
            name='payload',
            field=models.BinaryField(blank=True, default=b''),
        ),
    ]
